### ISSUE TITLE
data restapi_object causes panic on returned data

### ISSUE THREAD

**Issue by mlosapio** [Mastercard/terraform-provider-restapi#14]
I'm running into an issue where the provider is bombing out on the data restapi_object returned values. I've validated that the returned payload is valid json. 

Thoughts?

```
data "restapi_object" "account_uuid" {
  path         = "/Accounts"
  search_key   = "name"
  search_value = "${var.account_name}"
  results_key  = "id"
  debug        = true
}
```

```
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: panic: interface conversion: interface {} is []interface {}, not map[string]interface {}
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: goroutine 38 [running]:
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: github.com/Mastercard/terraform-provider-restapi/restapi.dataSourceRestApiRead(0xc420343490, 0x185a9e0, 0xc420372090, 0xc420343490, 0x0)
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/root/go/src/github.com/Mastercard/terraform-provider-restapi/restapi/datasource_api_object.go:106 +0xe96
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc420450af0, 0xc42033b0c0, 0x185a9e0, 0xc420372090, 0xc4203c6e58, 0x10b9b01, 0x17ef5e0)
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/root/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:292 +0x88
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc420450b60, 0xc420332780, 0xc42033b0c0, 0x18, 0x18, 0xc42033b100)
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/root/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:426 +0x9a
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataApply(0xc4203b7660, 0xc42032b710, 0xc42032b880, 0x0, 0x0)
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/root/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:604 +0x4e
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: reflect.Value.call(0xc42013b320, 0xc4203340e8, 0x13, 0x197a629, 0x4, 0xc4203adf18, 0x3, 0x3, 0xc4203362c0, 0x20002, ...)
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/usr/local/go/src/reflect/value.go:447 +0x969
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: reflect.Value.Call(0xc42013b320, 0xc4203340e8, 0x13, 0xc420051718, 0x3, 0x3, 0xc42045e240, 0x13dcc1b, 0x1)
2018-08-31T18:57:41.615-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/usr/local/go/src/reflect/value.go:308 +0xa4
2018-08-31T18:57:41.616-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: net/rpc.(*service).call(0xc420336300, 0xc420332640, 0xc42032c340, 0xc42032c350, 0xc420366600, 0xc42033a320, 0x17ef5a0, 0xc42032b710, 0x16, 0x17ef5e0, ...)
2018-08-31T18:57:41.616-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/usr/local/go/src/net/rpc/server.go:384 +0x14e
2018-08-31T18:57:41.616-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: created by net/rpc.(*Server).ServeCodec
2018-08-31T18:57:41.616-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/usr/local/go/src/net/rpc/server.go:480 +0x43a
2018/08/31 18:57:41 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.restapi_object.account_uuid: unexpected EOF
2018/08/31 18:57:41 [ERROR] root: eval: *terraform.EvalSequence, err: data.restapi_object.account_uuid: unexpected EOF
2018/08/31 18:57:41 [TRACE] [walkRefresh] Exiting eval tree: data.restapi_object.account_uuid
2018/08/31 18:57:41 [TRACE] dag/walk: upstream errored, not walking "provider.restapi (close)"
```

**Comment by DRuggeri** [comment]
Interesting - this is the part of the code that casts the returned object to a hash. It looks like it is saying that the item it picked is an array rather than a single element. Did you get the `results_key` correct? A few more lines leading up to this with TF_LOG set to 1 may be able to shed some light on why it is failing.

My suspicion is that the value entered for `results_key` may need one additional path parameter... but there's no doubt that the provider should not panic and should instead provide a useful error message. If you have some sample JSON (sanitize the real output as you see fit), I can see about working up a test case to cover this and similar errors.

**Comment by mlosapio** [comment]
So I better understand the purpose of `results_key` and turns out I didn't need it. However I'm getting a new error... 

Immediately after receiving the json (ID isn't a string but a float)

```
2018-09-05T17:04:26.083-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: panic: interface conversion: interface {} is float64, not string
2018-09-05T17:04:26.083-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 
2018-09-05T17:04:26.083-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: goroutine 14 [running]:
2018-09-05T17:04:26.083-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: github.com/Mastercard/terraform-provider-restapi/restapi.dataSourceRestApiRead(0xc420289f10, 0x185a9e0, 0xc4201d5d40, 0xc420289f10, 0x0)
2018-09-05T17:04:26.083-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/root/go/src/github.com/Mastercard/terraform-provider-restapi/restapi/datasource_api_object.go:128 +0xe26
2018-09-05T17:04:26.083-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc4203b8a80, 0xc4203293a0, 0x185a9e0, 0xc4201d5d40, 0xc4203a1198, 0x10b9b01, 0x17ef5e0)
2018-09-05T17:04:26.083-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/root/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:292 +0x88
2018-09-05T17:04:26.083-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc4203b8af0, 0xc4200a19a0, 0xc4203293a0, 0x18, 0x18, 0xc4203293e0)
2018-09-05T17:04:26.083-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/root/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:426 +0x9a
2018-09-05T17:04:26.083-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataApply(0xc42037aa40, 0xc42043f1c0, 0xc42043f330, 0x0, 0x0)
2018-09-05T17:04:26.083-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/root/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:604 +0x4e
2018-09-05T17:04:26.083-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: reflect.Value.call(0xc42033c660, 0xc42000cad0, 0x13, 0x197a629, 0x4, 0xc42006ff18, 0x3, 0x3, 0xc420192c80, 0xc4203866e8, ...)
2018-09-05T17:04:26.084-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/usr/local/go/src/reflect/value.go:447 +0x969
2018-09-05T17:04:26.084-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: reflect.Value.Call(0xc42033c660, 0xc42000cad0, 0x13, 0xc420386718, 0x3, 0x3, 0xc420390000, 0xc400000002, 0x0)
2018-09-05T17:04:26.084-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/usr/local/go/src/reflect/value.go:308 +0xa4
2018-09-05T17:04:26.084-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: net/rpc.(*service).call(0xc420193480, 0xc4200a1860, 0xc42028ca80, 0xc42028ca90, 0xc420151380, 0xc420328600, 0x17ef5a0, 0xc42043f1c0, 0x16, 0x17ef5e0, ...)
2018-09-05T17:04:26.084-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/usr/local/go/src/net/rpc/server.go:384 +0x14e
2018-09-05T17:04:26.084-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: created by net/rpc.(*Server).ServeCodec
2018-09-05T17:04:26.084-0400 [DEBUG] plugin.terraform-provider-restapi_v1.2.1-darwin-amd64: 	/usr/local/go/src/net/rpc/server.go:480 +0x43a
2018/09/05 17:04:26 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.restapi_object.account_uuid: unexpected EOF
2018/09/05 17:04:26 [ERROR] root: eval: *terraform.EvalSequence, err: data.restapi_object.account_uuid: unexpected EOF
2018/09/05 17:04:26 [TRACE] [walkRefresh] Exiting eval tree: data.restapi_object.account_uuid
2018/09/05 17:04:26 [TRACE] dag/walk: upstream errored, not walking "provider.restapi (close)"
```

My JSON is basically like this:

 curl -X GET https://myapi.com/v2/Groups

```
[
    {
        "description": "name1",
        "id": 1,
        "name": "name1",
        "permissions": {
            "access": [],
            "create": [],
            "crossAccountAccess": [],
            "manage": [],
            "view": [
                ""
            ]
        }
    },
    {
        "description": "name2",
        "id": 2,
        "name": "name2",
        "permissions": {
            "access": [],
            "create": [],
            "crossAccountAccess": [],
            "manage": [],
            "view": [
                ""
            ]
        }
    },
    {
        "description": "name3",
        "id": 3,
        "name": "name3",
        "permissions": {
            "access": [],
            "create": [],
            "crossAccountAccess": [],
            "manage": [],
            "view": [
                ""
            ]
        }
    }
]
```

**Comment by DRuggeri** [comment]
Ah, OK - makes sense now :-)
That should be easy to solve for - we could just use sprintf to convert the value to string easily. I'll add a fix soon as well as some test cases around the provider.

I'll also plan to use the JSON you attached as the basis for a test case when searching for a bad path (to ensure the datasource returns a USEFUL error instead of a panic).

**Comment by DRuggeri** [comment]
So, I think this should be all set now. Can you try with the `1.2.2` release just created and let me know how it works?

**Comment by DRuggeri** [comment]
I also just added some more testing and type-safety stuff in `1.3.0`. Feel free to give that a go.

**Comment by mlosapio** [comment]
Rock on - looks like the issue is now resolved!
